"""initial schema (existing DB)

Revision ID: 72e0c2e50ce9
Revises: 
Create Date: 2025-11-02 16:43:24.246621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72e0c2e50ce9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('phone_number', sa.String(length=30), nullable=True),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'USER', 'SUPPLIER', name='roleenum'), nullable=False),
    sa.Column('is_2fa_enabled', sa.Boolean(), nullable=True),
    sa.Column('two_factor_method', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone_number'),
    sa.UniqueConstraint('username')
    )
    op.create_table('fee_rules',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('amount_sar', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('applies_to', sa.String(length=40), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fee_rules', schema=None) as batch_op:
        batch_op.create_index('idx_fee_active', ['is_active'], unique=False)

    op.create_table('price_rules',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('condition', sa.Enum('CATEGORY', 'BRAND', 'MIN_QTY', 'MIN_ORDER', name='priceruleconditionenum'), nullable=False),
    sa.Column('condition_value', sa.String(length=160), nullable=True),
    sa.Column('percent_off', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('sar_off', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('starts_at', sa.DateTime(), nullable=True),
    sa.Column('ends_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('price_rules', schema=None) as batch_op:
        batch_op.create_index('idx_price_rule_active', ['is_active'], unique=False)

    op.create_table('promos',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=True),
    sa.Column('percent_off', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('sar_off', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('min_order_sar', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('max_redemptions', sa.Integer(), nullable=True),
    sa.Column('per_user_limit', sa.Integer(), nullable=True),
    sa.Column('starts_at', sa.DateTime(), nullable=True),
    sa.Column('ends_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    with op.batch_alter_table('promos', schema=None) as batch_op:
        batch_op.create_index('idx_promos_code', ['code'], unique=False)

    op.create_table('tax_rules',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('rate_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('applies_to', sa.String(length=40), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tax_rules', schema=None) as batch_op:
        batch_op.create_index('idx_tax_active', ['is_active'], unique=False)

    op.create_table('warehouses',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('location', sa.String(length=160), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('webhook_events',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('kind', sa.String(length=80), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('webhook_events', schema=None) as batch_op:
        batch_op.create_index('idx_webhook_status', ['status'], unique=False)

    op.create_table('account_profiles',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('account_id', sa.BigInteger(), nullable=False),
    sa.Column('full_name', sa.String(length=160), nullable=True),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('locale', sa.String(length=10), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id')
    )
    with op.batch_alter_table('account_profiles', schema=None) as batch_op:
        batch_op.create_index('idx_account_profiles_account', ['account_id'], unique=False)

    op.create_table('account_security',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('account_id', sa.BigInteger(), nullable=False),
    sa.Column('is_2fa_enabled', sa.Boolean(), nullable=True),
    sa.Column('two_factor_method', sa.String(length=30), nullable=True),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('last_login_ip', sa.String(length=45), nullable=True),
    sa.Column('device_fingerprint', sa.String(length=120), nullable=True),
    sa.Column('is_locked', sa.Boolean(), nullable=True),
    sa.Column('locked_reason', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id')
    )
    with op.batch_alter_table('account_security', schema=None) as batch_op:
        batch_op.create_index('idx_account_security_account', ['account_id'], unique=False)

    op.create_table('addresses',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=True),
    sa.Column('full_name', sa.String(length=160), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('line1', sa.String(length=180), nullable=False),
    sa.Column('line2', sa.String(length=180), nullable=True),
    sa.Column('city', sa.String(length=80), nullable=False),
    sa.Column('state', sa.String(length=80), nullable=True),
    sa.Column('country', sa.String(length=80), nullable=False),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.create_index('idx_addresses_user_kind_default', ['user_id', 'kind', 'is_default'], unique=False)

    op.create_table('ai_sessions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('account_id', sa.BigInteger(), nullable=False),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('actor_account_id', sa.BigInteger(), nullable=True),
    sa.Column('entity', sa.String(length=40), nullable=True),
    sa.Column('entity_id', sa.BigInteger(), nullable=True),
    sa.Column('action', sa.String(length=40), nullable=True),
    sa.Column('before_json', sa.JSON(), nullable=True),
    sa.Column('after_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['actor_account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index('idx_audit_entity', ['entity', 'entity_id'], unique=False)

    op.create_table('carts',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('account_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id')
    )
    with op.batch_alter_table('carts', schema=None) as batch_op:
        batch_op.create_index('idx_cart_account', ['account_id'], unique=False)

    op.create_table('merge_groups',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('account_id', sa.BigInteger(), nullable=False),
    sa.Column('type', sa.Enum('SYSTEM', 'ORDER', 'PAYMENT', 'SECURITY', name='notifytypeenum'), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PAID', 'SHIPPED', 'DELIVERED', 'CANCELLED', name='orderstatusenum'), nullable=True),
    sa.Column('subtotal_sar', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('shipping_sar', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('customs_sar', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('fsa_fee_sar', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('handling_sar', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('merge_service_sar', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_sar', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('smartpick_personalization',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('account_id', sa.BigInteger(), nullable=False),
    sa.Column('pref_json', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', name='uq_sp_persona_account')
    )
    with op.batch_alter_table('smartpick_personalization', schema=None) as batch_op:
        batch_op.create_index('idx_sp_persona_account', ['account_id'], unique=False)

    op.create_table('suppliers',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('account_id', sa.BigInteger(), nullable=True),
    sa.Column('company_name', sa.String(length=120), nullable=True),
    sa.Column('contact_name', sa.String(length=120), nullable=True),
    sa.Column('rating', sa.Numeric(precision=2, scale=1), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id')
    )
    op.create_table('wishlists',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('account_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id')
    )
    with op.batch_alter_table('wishlists', schema=None) as batch_op:
        batch_op.create_index('idx_wishlist_account', ['account_id'], unique=False)

    op.create_table('ai_events',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('account_id', sa.BigInteger(), nullable=True),
    sa.Column('order_id', sa.BigInteger(), nullable=True),
    sa.Column('event_type', sa.Enum('RECOMMENDATION', 'PACKAGE_OPTIM', 'FRAUD_CHECK', 'NOTIFY', name='aieventenum'), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_messages',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('session_id', sa.BigInteger(), nullable=False),
    sa.Column('sender', sa.String(length=10), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['ai_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_messages', schema=None) as batch_op:
        batch_op.create_index('idx_ai_messages_session', ['session_id'], unique=False)

    op.create_table('invoices',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('order_id', sa.BigInteger(), nullable=True),
    sa.Column('merge_group_id', sa.BigInteger(), nullable=True),
    sa.Column('invoice_number', sa.String(length=40), nullable=False),
    sa.Column('invoice_type', sa.Enum('SOLO', 'SHARED', name='invoicetypeenum'), nullable=True),
    sa.Column('issue_date', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('subtotal_sar', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('tax_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('fees_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('discount_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('total_sar', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('payment_status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['merge_group_id'], ['merge_groups.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_number')
    )
    op.create_table('merge_members',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('group_id', sa.BigInteger(), nullable=False),
    sa.Column('account_id', sa.BigInteger(), nullable=False),
    sa.Column('order_id', sa.BigInteger(), nullable=True),
    sa.Column('weight_kg', sa.Numeric(precision=8, scale=3), nullable=True),
    sa.Column('share_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('joined_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['merge_groups.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'account_id', name='uq_merge_member')
    )
    with op.batch_alter_table('merge_members', schema=None) as batch_op:
        batch_op.create_index('idx_merge_members_group', ['group_id'], unique=False)

    op.create_table('products',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('supplier_id', sa.BigInteger(), nullable=True),
    sa.Column('owner_user_id', sa.BigInteger(), nullable=True),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('sku', sa.String(length=80), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_primary', sa.Text(), nullable=True),
    sa.Column('origin', sa.Enum('AI', 'CATALOG', name='productoriginenum'), nullable=False),
    sa.Column('visibility', sa.Enum('PRIVATE', 'SMARTPICK', 'PUBLIC', name='productvisibilityenum'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('price_sar', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('base_price_sar', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('complexity_factor', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('category_multiplier', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('discount_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('final_price_sar', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('stock_qty', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=80), nullable=True),
    sa.Column('brand', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['owner_user_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sku')
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_index('idx_products_origin', ['origin'], unique=False)
        batch_op.create_index('idx_products_owner_visibility', ['owner_user_id', 'visibility'], unique=False)

    op.create_table('promo_redemptions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('promo_id', sa.BigInteger(), nullable=False),
    sa.Column('account_id', sa.BigInteger(), nullable=False),
    sa.Column('order_id', sa.BigInteger(), nullable=False),
    sa.Column('redeemed_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['promo_id'], ['promos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('promo_id', 'account_id', 'order_id', name='uq_promo_use')
    )
    with op.batch_alter_table('promo_redemptions', schema=None) as batch_op:
        batch_op.create_index('idx_redemption_promo', ['promo_id'], unique=False)

    op.create_table('return_requests',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('order_id', sa.BigInteger(), nullable=False),
    sa.Column('account_id', sa.BigInteger(), nullable=False),
    sa.Column('reason', sa.String(length=160), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('REQUESTED', 'AUTHORIZED', 'REJECTED', 'RECEIVED', 'REFUNDED', 'CLOSED', name='returnstatusenum'), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('return_requests', schema=None) as batch_op:
        batch_op.create_index('idx_return_order', ['order_id'], unique=False)

    op.create_table('shipment_batches',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('group_id', sa.BigInteger(), nullable=True),
    sa.Column('carrier', sa.String(length=80), nullable=True),
    sa.Column('tracking_no', sa.String(length=120), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('depart_at', sa.DateTime(), nullable=True),
    sa.Column('arrive_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['merge_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('support_tickets',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('account_id', sa.BigInteger(), nullable=False),
    sa.Column('order_id', sa.BigInteger(), nullable=True),
    sa.Column('subject', sa.String(length=160), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'IN_PROGRESS', 'RESOLVED', 'CLOSED', name='ticketstatusenum'), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('support_tickets', schema=None) as batch_op:
        batch_op.create_index('idx_ticket_account', ['account_id'], unique=False)

    op.create_table('ai_generations',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('session_id', sa.BigInteger(), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('prompt_json', sa.JSON(), nullable=True),
    sa.Column('meta_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['ai_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_generations', schema=None) as batch_op:
        batch_op.create_index('idx_ai_generations_session', ['session_id'], unique=False)

    op.create_table('ai_product_history',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('account_id', sa.BigInteger(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('description_before', sa.Text(), nullable=True),
    sa.Column('description_after', sa.Text(), nullable=True),
    sa.Column('image_url_before', sa.Text(), nullable=True),
    sa.Column('image_url_after', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cart_items',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('cart_id', sa.BigInteger(), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('unit_price_sar', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['cart_id'], ['carts.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cart_id', 'product_id', name='uq_cart_product_once')
    )
    op.create_table('inventory_movements',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('warehouse_id', sa.BigInteger(), nullable=True),
    sa.Column('move_type', sa.Enum('INBOUND', 'OUTBOUND', 'ADJUST', name='inventorymovementtypeenum'), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('ref', sa.String(length=160), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inventory_movements', schema=None) as batch_op:
        batch_op.create_index('idx_inventory_product', ['product_id'], unique=False)

    op.create_table('order_items',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('order_id', sa.BigInteger(), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('unit_price_sar', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id', 'product_id', name='uq_order_product_once')
    )
    op.create_table('payments',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('order_id', sa.BigInteger(), nullable=False),
    sa.Column('method', sa.Enum('CARD', 'PAYPAL', 'APPLE_PAY', name='paymentmethodenum'), nullable=True),
    sa.Column('amount_sar', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.Enum('INITIATED', 'AUTHORIZED', 'CAPTURED', 'FAILED', 'REFUNDED', name='paymentstatusenum'), nullable=True),
    sa.Column('txn_ref', sa.String(length=120), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('account_id', sa.BigInteger(), nullable=False),
    sa.Column('invoice_id', sa.BigInteger(), nullable=True),
    sa.Column('merge_group_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['merge_group_id'], ['merge_groups.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_images',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_ingredients',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('ingredient_name', sa.String(length=160), nullable=False),
    sa.Column('percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('role', sa.String(length=80), nullable=True),
    sa.Column('is_allergen', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_shades',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('shade_name', sa.String(length=80), nullable=False),
    sa.Column('hex_color', sa.String(length=7), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_skin_types',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('skin_type', sa.Enum('NORMAL', 'OILY', 'DRY', 'COMBINATION', 'SENSITIVE', name='skintypeenum'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'skin_type', name='uq_product_skin_type')
    )
    op.create_table('product_specs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('formula_base', sa.Enum('WATER', 'SILICONE', 'OIL', 'GEL', 'POWDER', 'CREAM', name='formulabaseenum'), nullable=True),
    sa.Column('coverage', sa.Enum('SHEER', 'MEDIUM', 'FULL', name='coverageenum'), nullable=True),
    sa.Column('finish', sa.Enum('MATTE', 'NATURAL', 'DEWY', 'GLOWY', name='finishenum'), nullable=True),
    sa.Column('spf', sa.Integer(), nullable=True),
    sa.Column('pa_rating', sa.String(length=10), nullable=True),
    sa.Column('pao_months', sa.Integer(), nullable=True),
    sa.Column('is_hypoallergenic', sa.Boolean(), nullable=True),
    sa.Column('is_non_comedogenic', sa.Boolean(), nullable=True),
    sa.Column('is_fragrance_free', sa.Boolean(), nullable=True),
    sa.Column('is_vegan', sa.Boolean(), nullable=True),
    sa.Column('is_cruelty_free', sa.Boolean(), nullable=True),
    sa.Column('net_content_value', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('net_content_unit', sa.String(length=10), nullable=True),
    sa.Column('made_in', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id')
    )
    op.create_table('reviews',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('account_id', sa.BigInteger(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='reviewstatusenum'), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'account_id', name='uq_review_once_per_user')
    )
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.create_index('idx_review_product', ['product_id'], unique=False)

    op.create_table('shipment_costs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('shipment_id', sa.BigInteger(), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('amount_sar', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipment_batches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('shipment_costs', schema=None) as batch_op:
        batch_op.create_index('idx_ship_costs_shipment', ['shipment_id'], unique=False)

    op.create_table('shipment_shares',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('shipment_id', sa.BigInteger(), nullable=False),
    sa.Column('account_id', sa.BigInteger(), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('amount_sar', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipment_batches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shipment_id', 'account_id', 'kind', name='uq_ship_share')
    )
    with op.batch_alter_table('shipment_shares', schema=None) as batch_op:
        batch_op.create_index('idx_ship_shares_ship_acc', ['shipment_id', 'account_id'], unique=False)

    op.create_table('smartpick_pool',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('added_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('reason', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id')
    )
    with op.batch_alter_table('smartpick_pool', schema=None) as batch_op:
        batch_op.create_index('idx_sp_pool_product', ['product_id'], unique=False)

    op.create_table('wishlist_items',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('wishlist_id', sa.BigInteger(), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['wishlist_id'], ['wishlists.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('wishlist_id', 'product_id', name='uq_wishlist_product_once')
    )
    op.create_table('ai_feedback',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('generation_id', sa.BigInteger(), nullable=False),
    sa.Column('account_id', sa.BigInteger(), nullable=False),
    sa.Column('feedback_type', sa.String(length=20), nullable=False),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['generation_id'], ['ai_generations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('refunds',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('payment_id', sa.BigInteger(), nullable=False),
    sa.Column('amount_sar', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.Enum('INITIATED', 'AUTHORIZED', 'CAPTURED', 'FAILED', 'REFUNDED', name='paymentstatusenum'), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('refunds', schema=None) as batch_op:
        batch_op.create_index('idx_refund_payment', ['payment_id'], unique=False)

    op.create_table('shipment_items',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('shipment_id', sa.BigInteger(), nullable=False),
    sa.Column('order_item_id', sa.BigInteger(), nullable=False),
    sa.Column('weight_kg', sa.Numeric(precision=8, scale=3), nullable=True),
    sa.Column('volume_cm3', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['order_item_id'], ['order_items.id'], ),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipment_batches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('shipment_items', schema=None) as batch_op:
        batch_op.create_index('idx_ship_items_shipment', ['shipment_id'], unique=False)

    op.drop_table('playing_with_neon')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('playing_with_neon',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('value', sa.REAL(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('playing_with_neon_pkey'))
    )
    with op.batch_alter_table('shipment_items', schema=None) as batch_op:
        batch_op.drop_index('idx_ship_items_shipment')

    op.drop_table('shipment_items')
    with op.batch_alter_table('refunds', schema=None) as batch_op:
        batch_op.drop_index('idx_refund_payment')

    op.drop_table('refunds')
    op.drop_table('ai_feedback')
    op.drop_table('wishlist_items')
    with op.batch_alter_table('smartpick_pool', schema=None) as batch_op:
        batch_op.drop_index('idx_sp_pool_product')

    op.drop_table('smartpick_pool')
    with op.batch_alter_table('shipment_shares', schema=None) as batch_op:
        batch_op.drop_index('idx_ship_shares_ship_acc')

    op.drop_table('shipment_shares')
    with op.batch_alter_table('shipment_costs', schema=None) as batch_op:
        batch_op.drop_index('idx_ship_costs_shipment')

    op.drop_table('shipment_costs')
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_index('idx_review_product')

    op.drop_table('reviews')
    op.drop_table('product_specs')
    op.drop_table('product_skin_types')
    op.drop_table('product_shades')
    op.drop_table('product_ingredients')
    op.drop_table('product_images')
    op.drop_table('payments')
    op.drop_table('order_items')
    with op.batch_alter_table('inventory_movements', schema=None) as batch_op:
        batch_op.drop_index('idx_inventory_product')

    op.drop_table('inventory_movements')
    op.drop_table('cart_items')
    op.drop_table('ai_product_history')
    with op.batch_alter_table('ai_generations', schema=None) as batch_op:
        batch_op.drop_index('idx_ai_generations_session')

    op.drop_table('ai_generations')
    with op.batch_alter_table('support_tickets', schema=None) as batch_op:
        batch_op.drop_index('idx_ticket_account')

    op.drop_table('support_tickets')
    op.drop_table('shipment_batches')
    with op.batch_alter_table('return_requests', schema=None) as batch_op:
        batch_op.drop_index('idx_return_order')

    op.drop_table('return_requests')
    with op.batch_alter_table('promo_redemptions', schema=None) as batch_op:
        batch_op.drop_index('idx_redemption_promo')

    op.drop_table('promo_redemptions')
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index('idx_products_owner_visibility')
        batch_op.drop_index('idx_products_origin')

    op.drop_table('products')
    with op.batch_alter_table('merge_members', schema=None) as batch_op:
        batch_op.drop_index('idx_merge_members_group')

    op.drop_table('merge_members')
    op.drop_table('invoices')
    with op.batch_alter_table('ai_messages', schema=None) as batch_op:
        batch_op.drop_index('idx_ai_messages_session')

    op.drop_table('ai_messages')
    op.drop_table('ai_events')
    with op.batch_alter_table('wishlists', schema=None) as batch_op:
        batch_op.drop_index('idx_wishlist_account')

    op.drop_table('wishlists')
    op.drop_table('suppliers')
    with op.batch_alter_table('smartpick_personalization', schema=None) as batch_op:
        batch_op.drop_index('idx_sp_persona_account')

    op.drop_table('smartpick_personalization')
    op.drop_table('orders')
    op.drop_table('notifications')
    op.drop_table('merge_groups')
    with op.batch_alter_table('carts', schema=None) as batch_op:
        batch_op.drop_index('idx_cart_account')

    op.drop_table('carts')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index('idx_audit_entity')

    op.drop_table('audit_logs')
    op.drop_table('ai_sessions')
    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.drop_index('idx_addresses_user_kind_default')

    op.drop_table('addresses')
    with op.batch_alter_table('account_security', schema=None) as batch_op:
        batch_op.drop_index('idx_account_security_account')

    op.drop_table('account_security')
    with op.batch_alter_table('account_profiles', schema=None) as batch_op:
        batch_op.drop_index('idx_account_profiles_account')

    op.drop_table('account_profiles')
    with op.batch_alter_table('webhook_events', schema=None) as batch_op:
        batch_op.drop_index('idx_webhook_status')

    op.drop_table('webhook_events')
    op.drop_table('warehouses')
    with op.batch_alter_table('tax_rules', schema=None) as batch_op:
        batch_op.drop_index('idx_tax_active')

    op.drop_table('tax_rules')
    with op.batch_alter_table('promos', schema=None) as batch_op:
        batch_op.drop_index('idx_promos_code')

    op.drop_table('promos')
    with op.batch_alter_table('price_rules', schema=None) as batch_op:
        batch_op.drop_index('idx_price_rule_active')

    op.drop_table('price_rules')
    with op.batch_alter_table('fee_rules', schema=None) as batch_op:
        batch_op.drop_index('idx_fee_active')

    op.drop_table('fee_rules')
    op.drop_table('accounts')
    # ### end Alembic commands ###
