"""Initial migration

Revision ID: eb52fa595d8e
Revises: 
Create Date: 2025-12-14 02:52:37.545019

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'eb52fa595d8e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_account_profiles_account'))

    with op.batch_alter_table('account_security', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_account_security_account'))
        batch_op.drop_column('locked_reason')
        batch_op.drop_column('is_locked')

    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=postgresql.ENUM('ADMIN', 'USER', 'SUPPLIER', name='roleenum'),
               type_=sa.Enum('ADMIN', 'USER', 'SUPPLIER', name='roleenum', schema='public'),
               existing_nullable=False)
        batch_op.alter_column('shipping_group_id',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('shipping_weight',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=3),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('shipping_product_cost',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('shipping_cost',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.create_index('idx_accounts_shipping_city_status', ['shipping_city', 'shipping_status'], unique=False)
        batch_op.create_index('idx_accounts_shipping_group', ['shipping_group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_accounts_shipping_group_id'), ['shipping_group_id'], unique=False)
        batch_op.drop_column('shipping_confirmed_at')
        batch_op.drop_column('shipping_confirmed')

    with op.batch_alter_table('ai_messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=20), nullable=False))
        batch_op.drop_column('sender')

    with op.batch_alter_table('ai_sessions', schema=None) as batch_op:
        batch_op.drop_column('notes')

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_column('merge_group_id')

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('payments_invoice_id_fkey'), type_='foreignkey')
        batch_op.drop_column('invoice_id')
        batch_op.drop_column('merge_group_id')

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('origin',
               existing_type=postgresql.ENUM('AI', 'CATALOG', name='productoriginenum'),
               type_=sa.Enum('AI', 'CATALOG', name='productoriginenum', schema='public'),
               existing_nullable=False)
        batch_op.alter_column('visibility',
               existing_type=postgresql.ENUM('PRIVATE', 'SMARTPICK', 'PUBLIC', name='productvisibilityenum'),
               type_=sa.Enum('PRIVATE', 'SMARTPICK', 'PUBLIC', name='productvisibilityenum', schema='public'),
               existing_nullable=False)
        batch_op.alter_column('status',
               existing_type=postgresql.ENUM('DRAFT', 'ACTIVE', 'ARCHIVED', name='productstatusenum'),
               type_=sa.Enum('DRAFT', 'ACTIVE', 'ARCHIVED', name='productstatusenum', schema='public'),
               existing_nullable=False)
        batch_op.drop_index(batch_op.f('idx_products_owner_visibility'))
        batch_op.create_index('idx_products_owner', ['owner_user_id'], unique=False)
        batch_op.drop_column('supplier_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('supplier_id', sa.BIGINT(), autoincrement=False, nullable=True))
        batch_op.drop_index('idx_products_owner')
        batch_op.create_index(batch_op.f('idx_products_owner_visibility'), ['owner_user_id', 'visibility'], unique=False)
        batch_op.alter_column('status',
               existing_type=sa.Enum('DRAFT', 'ACTIVE', 'ARCHIVED', name='productstatusenum', schema='public'),
               type_=postgresql.ENUM('DRAFT', 'ACTIVE', 'ARCHIVED', name='productstatusenum'),
               existing_nullable=False)
        batch_op.alter_column('visibility',
               existing_type=sa.Enum('PRIVATE', 'SMARTPICK', 'PUBLIC', name='productvisibilityenum', schema='public'),
               type_=postgresql.ENUM('PRIVATE', 'SMARTPICK', 'PUBLIC', name='productvisibilityenum'),
               existing_nullable=False)
        batch_op.alter_column('origin',
               existing_type=sa.Enum('AI', 'CATALOG', name='productoriginenum', schema='public'),
               type_=postgresql.ENUM('AI', 'CATALOG', name='productoriginenum'),
               existing_nullable=False)

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('merge_group_id', sa.BIGINT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('invoice_id', sa.BIGINT(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('payments_invoice_id_fkey'), 'invoices', ['invoice_id'], ['id'])

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('merge_group_id', sa.BIGINT(), autoincrement=False, nullable=True))

    with op.batch_alter_table('ai_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True))

    with op.batch_alter_table('ai_messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sender', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
        batch_op.drop_column('role')

    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shipping_confirmed', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('shipping_confirmed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.drop_index(batch_op.f('ix_accounts_shipping_group_id'))
        batch_op.drop_index('idx_accounts_shipping_group')
        batch_op.drop_index('idx_accounts_shipping_city_status')
        batch_op.alter_column('shipping_cost',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('shipping_product_cost',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('shipping_weight',
               existing_type=sa.Numeric(precision=10, scale=3),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('shipping_group_id',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('role',
               existing_type=sa.Enum('ADMIN', 'USER', 'SUPPLIER', name='roleenum', schema='public'),
               type_=postgresql.ENUM('ADMIN', 'USER', 'SUPPLIER', name='roleenum'),
               existing_nullable=False)

    with op.batch_alter_table('account_security', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_locked', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('locked_reason', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
        batch_op.create_index(batch_op.f('idx_account_security_account'), ['account_id'], unique=False)

    with op.batch_alter_table('account_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_account_profiles_account'), ['account_id'], unique=False)

    # ### end Alembic commands ###
